### ISSUE TITLE
While I'm on a roll with the good ideas!  

### ISSUE THREAD

**Issue by k2skaterii** [steppsr/taxtran#7]
This is another one that isn't a "you" problem.  But it's a problem for anyone who exports their transactions and uses that data for their taxes... 

My Current Wallet balance is 0.000008843661 XCH.  I added all of my incoming transactions & subtracted all of my outgoing transactions... The total should be 0.000008843661 XCH - but it wasn't.  My Excel-Math came up with a total of 0.154114409883 XCH. 

I haven't figured out exactly where the discrepancy is coming from, some is coming from the pain in the ass incoming transactions as "change" from outgoing transactions.   

What can you do to help here?  I didn't see anything that would help identify a change transaction vs a real (taxable) incoming transaction.  Including the destination wallet address might help identify the incoming transactions that are not taxable transactions.  Maybe?

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/kenny/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/kenny/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Date / Time | Transaction Amount |   | Transaction   Type | Comment
-- | -- | -- | -- | --
9/18/2021 2:06 | 0.000100000000 | 0 | OUTGOING_TX | Out Going to Exchange Wallet
9/18/2021 2:28 | 0.149900000000 | 0 | INCOMING_TX | Change from out going transaction
9/18/2021 2:28 | 0.100000000000 | 0 | OUTGOING_TX | Out Going to Exchange Wallet
9/18/2021 2:38 | 0.004205485008 | 0 | INCOMING_TX | Change from out going transaction
9/18/2021 2:38 | 0.750000000000 | 0 | OUTGOING_TX | Out Going to Exchange Wallet
9/18/2021 3:17 | 0.205169876738 | 0 | OUTGOING_TX | Out Going to Exchange Wallet

</body>

</html>

**Comment by steppsr** [comment]
Good question. I probably didn't consider this during my testing because I haven't sent out any Chia from my wallet. I'm wondering if you are totaling only the OUTGOING and INCOMING, if you might need to include other transaction types as well... specifically the FEE_REWARD for the payout to farmers who won a block, and the COINBASE_REWARD if winning a block if you are solo farming (in a pool this would go to the pool).

Would you be willing to send me the full transaction CSV file to analyze? If not I understand, but having some real data to review would be helpful. 

---

![signature](https://user-images.githubusercontent.com/274742/162579031-34b00486-bbb1-4b24-9f26-f76696f8e53f.png)

**Comment by k2skaterii** [comment]
you have mail

**Comment by steppsr** [comment]
Released new version 0.2 that rebuilt the extract into one script. Now builds CSV file from json file extracted from wallet db instead of doing chia wallet commands.
